# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- script: npm install -g @usebruno/cli
  displayName: 'Install Bruno CLI'

- script: cd collections
  displayName: 'Change working directory to collections'

- script: bru run --env qa --output results.html --format html --tests-only
  displayName: 'Run Bruno tests'
