name: Run Bruno Tests

on:
  push:
    branches:
      - main

jobs:
  run-bruno-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js environment
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install Bruno CLI
        run: npm install -g @usebruno/cli

      - name: Change working directory to pos
        run: cd pos

      - name: Run Bruno tests
        run: bru run --env qa --output ./results.html --format html --tests-only

      - name: Upload test results
        uses: actions/upload-artifact@v3
        with:
          name: test-results
          path: pos/results.html
